---
resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/MarkusKNyland/PGR301Exam-App/
      branch: master

inputs:
  - name: tasks

jobs:
  - name: compile-app
    plan:
      - get: source-code
        trigger: true
      - task: first-task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: maven
              tag: 3-jdk-8-slim
          inputs:
            - name: source-code
          output:
            - name: maven-cache
          caches:
            - path: source-code/m2
          run:
            path: bash
            args:
              - -c
              - |
                set -e
                cd source-code
                rm -rf ~/.m2
                ln -fs $(pwd)/m2 ~/.m2
                mvn clean compile
                cp -r $(pwd)/m2 maven-cache
      - task:
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: ubuntu
            inputs:
              - name: maven-cache
            run:
              path: find
              args: [.]
