---
resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/MarkusKNyland/PGR301Exam-App/
      branch: master

inputs:
  - name: tasks

jobs:
  - name: compile-app
    plan:
      - get: source-code
      - task: first-task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: maven
              tag: 3-jdk-8-slim
          inputs:
            - name: source-code
          run:
            path: /bin/bash
            args: ["source-code/tasks/package.sh"]